sudo: required
services:
  - docker

before_install:
  - docker build -t suhasram95/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true suhasram95/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: react-docker
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-147411271495
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
